### ISSUE TITLE
Cannot use WiFi with spaces in the name - and where is the firmware source code ?

### ISSUE THREAD

**Issue by gitcnd** [Freenove/Freenove_ESP32_Dog_Firmware#1]
I've fixed this bug in other firmware - a popular online wifi lib wrongly thinks a space is a terminator in a wifi SSID - easy to fix.  But...

Where is the source code for the *.bin firmware files?  I can't fix this, if you haven't published it somewhere...

**Comment by Zhentao-Lin** [comment]
This repository is the source location. The bin file location is in another repository.
https://github.com/Freenove/Freenove_Robot_Dog_Kit_for_ESP32/tree/main/Code/firmware

**Comment by Zhentao-Lin** [comment]
This is where the source code for the robot dog is located.
https://github.com/Freenove/Freenove_ESP32_Dog_Firmware/tree/main/main

**Comment by gitcnd** [comment]
Curious - it worked fine today (space in the SSID), but failed half-a-dozen times yesterday.
